replicaCount: 1
fullnameOverride: backend-helm
autoscaling:
  enabled: false

image:
  repository: backend-helm
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: false
  name: ""

podAnnotations: {}
podLabels: {}

imagePullSecrets: []

podSecurityContext: {}
securityContext: {}

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
 
readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
 
resources: {}

volumeMounts: []
volumes: []

nodeSelector: {}
affinity: {}
tolerations: []

ingress:
  enabled: true
  className: ""
  annotations: {}
  tls: []
  hosts:
    - host: edpDefault
      paths:
        - path: /
          pathType: ImplementationSpecific
  dnsWildcard: development.krci-dev.cloudmentor.academy
